name: Build pjsip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          ndk: 21.4.7075529

      - name: Build pjsip for Android
        run: |
          export ANDROID_NDK_ROOT=$ANDROID_NDK_HOME
          ./configure-android --use-ndk-cmake --ndk-home=$ANDROID_NDK_HOME
          make

  ios-build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build pjsip for iOS
        run: |
          ./configure-ios --with-openssl
          make -j8
