name: CI Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          ndk: 21.4.7075529

      - name: Build pjsip for Android
        run: |
          echo -e "#define PJ_CONFIG_ANDROID 1\n#include <pj/config_site_sample.h>" >> pjlib/include/pj/config_site.h
          export ANDROID_NDK_ROOT=$ANDROID_NDK_HOME
          ./configure-android
          make

      - name: Create Android release zip
        run: |
          mkdir -p release/android
          cp -r build/lib/*.a release/android/
          cp */include release/android -r
          cd release
          zip -r android-pjsip.zip android

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "release/android-pjsip.zip"
          asset_name: android-pjsip-build.zip
          tag: output-${{ github.ref }}
          overwrite: true
